steps:
# Build the container image
- name: maven:3.3-jdk-8
  entrypoint: mvn
  args: ['clean package com.google.cloud.tools:jib-maven-plugin:2.8.0:build -Dimage=gcr.io/testingiamproject-369302/build-run-image:v1 -DskipTests']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/build-run-image']
# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'cloud-run-deploy', '--image', 'gcr.io/$PROJECT_ID/build-run-image', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
images:
- gcr.io/$PROJECT_ID/build-run-image
